Various improvements
pierrechevalier83/2048-rs pull request #3
Opened 2022-02-08 03:22 UTC by StratusFearMe21

I reduced the number of allocations made by this program overall, and I updated the versions of all of the respective libraries. I also switched from `termion` to `crossterm` to add partial Windows compatibility

2022-02-08 21:02 UTC, pierrechevalier83 requested changes
Thanks for the PR, it's a nice refactor, and I like the idea to use `crossterm` to enable cross-platform functionality. I'm just wondering whether these 2 commits from @jackpot51 from 2017 were committed intentionally as part of this PR. If not, could you rebase your branch to exclude them? I'm OK with updating the cargo.lock, but I'd rather not remove the aur submodule without a reason for it.

2022-02-08 21:02 UTC, pierrechevalier83 commented on .gitmodules
> -[submodule "aur/2048-rs"]
Was this removal intentional? If so, what's the motivation for it?

2022-02-12 21:19 UTC, StratusFearMe21 commented on .gitmodules
> -[submodule "aur/2048-rs"]
Whoops, that removal was not intentional

2022-02-12 21:28 UTC, StratusFearMe21 commented
Sorry about that, I started this PR from the repo on https://gitlab.redox-os.org/redox-os/2048-rs

2022-02-12 22:31 UTC, pierrechevalier83 approved these changes
Thanks so much for the refactoring :smile: LGTM

2022-02-12 22:31 UTC, merged